# Generated by Django 3.2.16 on 2023-09-28 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0015_set_managed_to_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeraNotification',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('topic', models.CharField(db_column='Topic', max_length=255)),
                ('operation', models.CharField(db_column='Operation', max_length=255)),
                ('datetime_received', models.DateTimeField(db_column='ReceivedAt', default=datetime.datetime.now)),
                ('context', models.CharField(db_column='Context', max_length=255)),
                ('status', models.CharField(db_column='Status', max_length=255)),
                ('datetime_processed', models.DateTimeField(blank=True, db_column='ProcessedAt', null=True)),
            ],
            options={
                'db_table': 'tblHeraNotification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeraSubscription',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('uuid', models.UUIDField(db_column='UUID', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=datetime.datetime.now)),
                ('active', models.BooleanField(db_column='IsActive', default=True)),
                ('topic', models.CharField(db_column='Topic', max_length=255)),
            ],
            options={
                'db_table': 'tblHeraSubscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeraLocationIDsMapping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hera_code', models.CharField(db_column='HeraCode', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=datetime.datetime.now)),
                ('last_access', models.DateTimeField(db_column='LastAccess', default=datetime.datetime.now)),
                ('is_instance_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('location_type', models.CharField(db_column='LocationType', max_length=1)),
                ('openimis_location', models.ForeignKey(db_column='OpenIMISID', on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
            ],
            options={
                'db_table': 'tblHeraLocationIDsMapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeraHFIDsMapping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hera_code', models.CharField(db_column='HeraCode', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=datetime.datetime.now)),
                ('last_access', models.DateTimeField(db_column='LastAccess', default=datetime.datetime.now)),
                ('is_instance_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('openimis_hf', models.ForeignKey(db_column='OpenIMISID', on_delete=django.db.models.deletion.DO_NOTHING, to='location.healthfacility')),
            ],
            options={
                'db_table': 'tblHeraHFIDsMapping',
                'managed': True,
            },
        ),
    ]
