# Generated by Django 3.2.16 on 2023-10-12 13:37

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
        ('ecrvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herasubscription',
            name='created_by',
            field=models.IntegerField(db_column='CreatedBy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herasubscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='DeletedAt', null=True),
        ),
        migrations.AddField(
            model_name='herasubscription',
            name='deleted_by',
            field=models.IntegerField(blank=True, db_column='DeletedBy', null=True),
        ),
        migrations.CreateModel(
            name='HeraSubscriptionMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hera_subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='ecrvs.herasubscription')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hera_subscriptions', to='core.mutationlog')),
            ],
            options={
                'db_table': 'ecrvs_HeraSubscriptionMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
